#pragma once
#include <string>
#include <DXRuntime/Device.h>
#include <Resource/Mesh.h>
#include <Resource/DescriptorHeap.h>
#include <tiny_obj_loader/tiny_obj_loader.h>
#include <Component/Log.h>
#include <Component/RenderItem.h>
#include <DirectXMath.h>
#include <unordered_map>
#include <Component/stb_loader.h>
#include <filesystem>
#include <DXRuntime/FrameResource.h>
#include <Component/Material.h>